displayName=Friendscape Events
author=idyet
build=standard
description=Tracks your progress in Friendscape clan Events: bingo, Skill of the week, Boss of the week
tags=bingo,clan,event,sotw,botw,competition,friendscape
plugins=com.friendscape.FriendscapePlugin
